### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by JonathanHope** [isamert/jsdoc.el#6]
I love the idea of this package. With the new typescript-ts-mode and eglot in 29 a lot of what tide offers is already in Emacs. However it seems like this package doesn't support TypeScript. Here was the result of me adding docs to a function:

```
/**
 * 
 * @param {nil} nil - 
 * @param {nil} nil - 
 * @returns {number} - 
 */
function test(param1: string, param2: number): number {
  return 0;
}
```

Are there any plans to support TypeScript? I doubt TypeScript users care much about the type annotations.

**Comment by isamert** [comment]
What you want for this specific example would be something like this, right?

```ts
/**
 *
 * @param param1 -
 * @param param2 -
 * @returns
 */
function test(param1: string, param2: number): number {
  return 0;
}
```

I think this can be done easily, I'll take a look at it as soon as possible.

**Comment by JonathanHope** [comment]
Yup what you have there is perfect! Thanks for taking a look!

**Comment by isamert** [comment]
Hi @JonathanHope 
I added basic TypeScript support. Can you test it if it works for you? Apart from what we established above, I also added `@typeParam` support too, so if you have type parameters in your function, they should also appear as `* @typeParam T -` for example.

**Comment by JonathanHope** [comment]
Tested and verified. Thank you so much!
