### ISSUE TITLE
Object methods generate an empty jsdoc comment

### ISSUE THREAD

**Issue by shartf** [isamert/jsdoc.el#7]
Hi, 

I've noticed that jsdoc.el is not able to generate a jsdoc annotation for object methods:

```js
/**
 * @param {*} number - 
 * @returns {*} - 
 */
function square(number) {
    const myObj = {
        /**
         * NO ANNOTATION GENERATED
         */
        nested: function (number) {return number * number}
    }
  return myObj.nested(number);
}
```

For a someone not familiar with internals of TreeSitter how much work would it be to implement it and where in code would be the starting point? 
Thanks you for the package!

**Comment by isamert** [comment]
Well I was about write an explanation of how you might approach this but
it turns out it was a one line change :D (Your cursor needs to be on the
"function" keyword for this to work)

If you are still interested in adding any other feature, let me know and
we can work on it together.

**Comment by shartf** [comment]
Hi, 
I have tested it but was not able to produce an annotation, unfortunately. It is certainly the current version - I've looked into the source available to emacs. 

I have placed the cursor on "function" and called jsdoc, as advised. Treesitter syntax tree looks valid for my amateur understanding of it. 
<img width="1392" alt="Screenshot 2024-09-17 at 11 09 05" src="https://github.com/user-attachments/assets/8f617437-fd2c-4945-a23a-605cc1c15d2a">

I am currently trying to debug the calls, but I need to go through the edebug manual in detail, I guess - it is a tad arcane :)

**Comment by isamert** [comment]
Hmm, can you do M-: (eval-expression) while you are on the "function"
keyword and then try to evaluate:

    (jsdoc--parse-generic-function-declaration (treesit-node-parent (treesit-node-at (point))))

It should return something like this:

    (:name nil :returns "*" :throws nil :params ((:name #("number" 0 6 ...) :type "*")) :type-params nil)

If so, please try to re-evaluate the `jsdoc--generate` function by going
to the end of it and doing C-x C-e (eval-last-sexp). Or you might simply
try restarting Emacs first.

If it's returning something else, please post what it returns and also
the result of the following on the same place:

    (treesit-node-parent (treesit-node-at (point)))

**Comment by isamert** [comment]
Also I pushed a change based on what I see from the treesitter syntax
tree you've shared. Can you also test that?

**Comment by shartf** [comment]
I've tried to debug it and I see the error - it was indeed due to missing ```function_expression```!

```elisp
(defun jsdoc--generate ()
  (let* ((curr-node (treesit-node-parent (treesit-node-at (point))))
         (curr-node-type (treesit-node-type curr-node)))
    (pcase curr-node-type ;;<-- fails because function_expression is absent below
      ("lexical_declaration"
       (jsdoc--parse-lexical-declaration curr-node)) 
      ((or "function_declaration" "method_definition" "function" "arrow_function") 
       (jsdoc--parse-generic-function-declaration curr-node)))))
```
Now it works and I also learned how to use edebug - win-win! Many thanks for your help!
